### PR TITLE
Use with-eval-after-load instead of eval-after-load.

### PR DESCRIPTION
**Pull request by foopang**

### CODE REVIEW

**Comment by rdallasgray** [comment]
Hey -- thanks for this. It would break compatibility with Emacs 24.3 though. That might be OK, if it offered a significant benefit. So far as I can see though, the only benefit would be to allow byte compilation of the forms inside `eval-after-load`, which doesn't seem, to me, to be worth the cost.

But I'm open to persuasion if you feel otherwise.

**Comment by foopang** [comment]
Hi @rdallasgray In Emacs 24.5, the key bindings for Company mode don’t work after https://github.com/rdallasgray/graphene/blob/master/graphene-editing.el#L149-L150. It works by changing `eval-after-load` to `with-eval-after-load`. However, I am not sure how to make it compatible with older versions of Emacs.

**Comment by rdallasgray** [comment]
I've tested with a fresh install of graphene in Emacs 24.5.1 and I can't reproduce this. Are you sure it isn't being caused by another package you have installed?

**Comment by foopang** [comment]
@rdallasgray I've already disabled all other packages, but I am still having the problem with Emacs 24.5.1 for Mac OS X. Basically, I want to navigate between completions with `M-n` and `M-p`.

**Comment by rdallasgray** [comment]
OK, I reproduced this; it was because of the binding of `ESC` to `company-abort`. A bit of investigation of this shows that it was probably bad manners, so I've removed it. Closing as the issue should now be fixed.

**Comment by foopang** [comment]
Thanks @rdallasgray

**Pull request closed without merging**
